package io.swagger.client.model;

import java.util.Objects;
import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

/**
 * Edge
 */
@javax.annotation.Generated(value = "class io.swagger.codegen.languages.JavaClientCodegen", date = "2017-09-04T08:23:56.671Z")
public class Edge {
  @SerializedName("id")
  private String id = null;

  @SerializedName("head")
  private String head = null;

  @SerializedName("tail")
  private String tail = null;

  @SerializedName("class")
  private String propertyClass = null;

  public Edge id(String id) {
    this.id = id;
    return this;
  }

   /**
   * Get id
   * @return id
  **/
  @ApiModelProperty(example = "8b79d958f3bb5b625808f490a3ec0ed6", required = true, value = "")
  public String getId() {
    return id;
  }

  public void setId(String id) {
    this.id = id;
  }

  public Edge head(String head) {
    this.head = head;
    return this;
  }

   /**
   * Get head
   * @return head
  **/
  @ApiModelProperty(example = "5f3246a92bef76fd58485e72dea7d9b7", required = true, value = "")
  public String getHead() {
    return head;
  }

  public void setHead(String head) {
    this.head = head;
  }

  public Edge tail(String tail) {
    this.tail = tail;
    return this;
  }

   /**
   * Get tail
   * @return tail
  **/
  @ApiModelProperty(example = "49ad16d29900f22e021467b46707130e", required = true, value = "")
  public String getTail() {
    return tail;
  }

  public void setTail(String tail) {
    this.tail = tail;
  }

  public Edge propertyClass(String propertyClass) {
    this.propertyClass = propertyClass;
    return this;
  }

   /**
   * Get propertyClass
   * @return propertyClass
  **/
  @ApiModelProperty(example = "PhoNetworksAutogenerated\UserOut\Post", value = "")
  public String getPropertyClass() {
    return propertyClass;
  }

  public void setPropertyClass(String propertyClass) {
    this.propertyClass = propertyClass;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Edge edge = (Edge) o;
    return Objects.equals(this.id, edge.id) &&
        Objects.equals(this.head, edge.head) &&
        Objects.equals(this.tail, edge.tail) &&
        Objects.equals(this.propertyClass, edge.propertyClass);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, head, tail, propertyClass);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Edge {\n");
    
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    head: ").append(toIndentedString(head)).append("\n");
    sb.append("    tail: ").append(toIndentedString(tail)).append("\n");
    sb.append("    propertyClass: ").append(toIndentedString(propertyClass)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
  
}

