package io.swagger.client.model;

import java.util.Objects;
import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.util.ArrayList;
import java.util.List;

/**
 * NodeEdge
 */
@javax.annotation.Generated(value = "class io.swagger.codegen.languages.JavaClientCodegen", date = "2017-09-04T08:23:56.671Z")
public class NodeEdge {
  @SerializedName("id")
  private String id = null;

  @SerializedName("classes")
  private List<String> classes = new ArrayList<String>();

  public NodeEdge id(String id) {
    this.id = id;
    return this;
  }

   /**
   * Get id
   * @return id
  **/
  @ApiModelProperty(example = "8b79d958f3bb5b625808f490a3ec0ed6", required = true, value = "")
  public String getId() {
    return id;
  }

  public void setId(String id) {
    this.id = id;
  }

  public NodeEdge classes(List<String> classes) {
    this.classes = classes;
    return this;
  }

  public NodeEdge addClassesItem(String classesItem) {
    this.classes.add(classesItem);
    return this;
  }

   /**
   * Get classes
   * @return classes
  **/
  @ApiModelProperty(example = "[&quot;PhoNetworksAutogenerated\\UserOut\\Post&quot;,&quot;Pho\\Kernel\\Foundation\\ActorOut\\Write&quot;,&quot;Pho\\Framework\\ActorOut\\Write&quot;,&quot;Pho\\Framework\\ActorOut\\Subscribe&quot;,&quot;Pho\\Framework\\AbstractEdge&quot;,&quot;Pho\\Lib\\Graph\\Edge&quot;]", required = true, value = "")
  public List<String> getClasses() {
    return classes;
  }

  public void setClasses(List<String> classes) {
    this.classes = classes;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    NodeEdge nodeEdge = (NodeEdge) o;
    return Objects.equals(this.id, nodeEdge.id) &&
        Objects.equals(this.classes, nodeEdge.classes);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, classes);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class NodeEdge {\n");
    
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    classes: ").append(toIndentedString(classes)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
  
}

